### ISSUE TITLE
usage of fetch

### ISSUE THREAD

**Issue by bertsky** [liberapay/git-lfs-fetch.py#12]
I am having difficulty understanding how to use `fetch`. If I do not pass a `checkout_dir` (which I would expect to be generated from the last path component of `git_repo` as in `git clone URL`), then it says `Can't checkout into a bare repo`. If I do pass some `checkout_dir`, then I run into this:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/git_lfs/__init__.py", line 165, in fetch
    with TempDir(dir=checkout_dir) as d:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.8/site-packages/git_lfs/utils.py", line 33, in TempDir
    d = mkdtemp(**kw)
  File "/usr/lib/python3.8/tempfile.py", line 498, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: 'test/tmp9jicu15s'
```
So this obviously expects an _existing_ directory. Why?

**Comment by Changaco** [comment]
Requiring an existing directory was most likely unintentional. Again, I encourage you to make a pull request to fix the problem.

**Comment by bertsky** [comment]
Ok, I will, but allow me to understand how usage was meant to work. 
https://github.com/liberapay/git-lfs-fetch.py/blob/23026ff916065ee113cdc898e2670f6d9587a1a5/git_lfs/__init__.py#L163-L169

Why the `os.rename`? Why even a temporary directory in the first place?

**Comment by Changaco** [comment]
Creating a temporary file or directory, then renaming it, is a way of making changes atomically.

I don't remember if the code was written this way merely as a precaution or if I actually needed this “safety” at the time.

**Comment by bertsky** [comment]
Understood. It would help if you could divulge one concrete example of a call (API or CLI) that used to succeed. I'm sure I can take it from there and reconstruct the intended implementation.

**Comment by Changaco** [comment]
The call was `python -m git_lfs -vv ~/git/$OPENSHIFT_APP_NAME.git $OPENSHIFT_REPO_DIR`.

**Comment by bertsky** [comment]
> The call was `python -m git_lfs -vv ~/git/$OPENSHIFT_APP_NAME.git $OPENSHIFT_REPO_DIR`.

Oh, then my impression that this was also meant for **remote** repos (first cloning https or git URLs) was wrong to begin with?

**Comment by Changaco** [comment]
The code was never meant to be invoked with URLs of remote repositories.
