### ISSUE TITLE
Use on Read The Docs

### ISSUE THREAD

**Issue by bmorris3** [liberapay/git-lfs-fetch.py#9]
Hi, 

Thanks for this great package! 

I have an [almost-functional workflow](https://github.com/bmorris3/kelp/blob/c535c7b40dda67a463a59114316607c52cb05d6c/docs/conf.py#L198-L201) for getting an `lfs` file in my Read The Docs build, but it's [failing with this error](https://readthedocs.org/projects/kelp/builds/13258976/): 
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/kelp/conda/latest/lib/python3.9/site-packages/sphinx/config.py", line 326, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kelp/conda/latest/lib/python3.9/site-packages/sphinx/util/pycompat.py", line 88, in execfile_
    exec(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kelp/checkouts/latest/docs/conf.py", line 201, in <module>
    git_lfs.fetch(os.path.join(os.path.dirname(__file__), os.path.pardir))
  File "/home/docs/checkouts/readthedocs.org/user_builds/kelp/conda/latest/lib/python3.9/site-packages/git_lfs/__init__.py", line 207, in fetch
    lfs_url, lfs_auth_info = get_lfs_endpoint_url(git_repo, checkout_dir)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kelp/conda/latest/lib/python3.9/site-packages/git_lfs/__init__.py", line 60, in get_lfs_endpoint_url
    auth_header = get_lfs_api_token(host, path)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kelp/conda/latest/lib/python3.9/site-packages/git_lfs/__init__.py", line 72, in get_lfs_api_token
    output = check_output(query_cmd.split()).strip().decode('utf8')
  File "/home/docs/checkouts/readthedocs.org/user_builds/kelp/conda/latest/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/docs/checkouts/readthedocs.org/user_builds/kelp/conda/latest/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ssh', 'git@github.com', 'git-lfs-authenticate', '/bmorris3/kelp.git', 'download']' returned non-zero exit status 255.
```
Do you have any pointers on what this error means? Thanks in advance.

**Comment by Changaco** [comment]
It means that downloading the file through SSH isn't working, probably because the RtD server doesn't allow your script to use SSH, for security reasons.

**Comment by bmorris3** [comment]
Thanks so much for the tip! Trying [this workaround](https://github.com/readthedocs/readthedocs.org/issues/1846#issuecomment-477184259) now, will close the issue since it's not actually a git-lfs error.
